/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bighoon' at '04/11/15 12:16 PM' with Gradle 2.6
 *
 * @author bighoon, @date 04/11/15 12:16 PM
 */

import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.Field;
import java.util.IdentityHashMap;
import java.util.Map;

import org.jdom2.DocType;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

public class Library {
	private static Integer id = 0;
	private Map<Object, Integer> serializedMap = new IdentityHashMap<Object, Integer>();
	public Library()
	{
		try
		{
			serialize(new ClassB());
		}
		catch (Exception e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
    public Integer serialize(Object obj) throws IllegalArgumentException, IllegalAccessException, IOException {
    	Field[] fields = obj.getClass().getDeclaredFields();
    	System.out.println(fields.length);
    	
    	Element thisNode = null;
    	thisNode = new Element("object")
    			.setAttribute("class", obj.getClass().getName())
    			.setAttribute("id", String.valueOf(id));
    	
    	serializedMap.put(obj, id);
    	id++;
    	
    	// for each field add an element
    	for( Field field : fields)
    	{
    		field.setAccessible(true);
    		Element newFieldElement = new Element("field")
    								.setAttribute("name", field.getName())
    								.setAttribute("declaringclass", field.getDeclaringClass().getName());
    		if (field.getType().isPrimitive())
    		{
				newFieldElement.addContent(new Element("value")
											.setText(field.get(obj).toString()));
    		}
    		else // field is a reference
    		{
				if (field.get(obj) != null && serializedMap.get(field.get(obj).getClass()) == null)
				{
					Integer newId = serialize(field.get(obj));
					
					newFieldElement.addContent(new Element("reference")
											.setText(String.valueOf(newId)));
				}
    		}
    		thisNode.addContent(newFieldElement);
    	}
    	// for each element in array get its value or reference
    	// for each non-primitive recursively get its tree

    	
    	if (serializedMap.get(obj) != null && serializedMap.get(obj) == 0)
    	{
			Document doc = new Document(thisNode);
			doc.setDocType(new DocType("rooty"));
		
			System.out.println(doc.toString());
		
			XMLOutputter xmlOutput = new XMLOutputter();
			xmlOutput.setFormat(Format.getPrettyFormat());
			
			OutputStream outStream = System.out;
			xmlOutput.output(doc, outStream);
    	}
    	
		return serializedMap.get(obj);
    }
    
    public static void main(String[] args)
    {
    	new Library();
    }
}
