import java.util.Scanner;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bighoon' at '13/11/15 6:05 PM' with Gradle 2.6
 *
 * @author bighoon, @date 13/11/15 6:05 PM
 */
public class Driver {
	private static Scanner in = new Scanner(System.in);
	private static ObjectCreator objCreator = new ObjectCreator();
	public static void main(String[] args)
	{
		boolean loop = true;
		while (loop)
		{
			System.out.println("\n\t++++++ Main Menu ++++++");
			System.out.println("1: \t Object Creator");
			System.out.println("2: \t View Objects Created");
			System.out.println("3: \t send to server");
			System.out.println("4: \t listen as server (received stream written to file)");
			System.out.println("5: \t deserialize from file");
			System.out.println("6: \t quit");
			//print main menu
			int input = in.nextInt();
			
			switch (input)
			{
				case 1: // enter the object creator
					objCreator.menu();
					break;
				case 2: // view created objects
					objCreator.viewObjects();
					break;
				case 3:
					break;
				case 4:
					break;
				case 5:
					break;
				case 6:
					loop = false;
			}
		}
	}
}
